const questions = [
	{
		type: "list",
		name: "select",
		message: "What would you like to do?",
		choices: [
			"Add Employee",
			"View All Employees",
			"Update Employee Role",
			"Add Role",
			"View All Roles",
			"Add Department",
			"View All Departments",
			"Quit",
		],
	},
	{
		type: "input",
		name: "deptName",
		message: "What is the name of the department?",
		validate: (answer) => validateString(answer),
		when: (prev) => prev.select === "Add Department",
	},
	{
		type: "input",
		name: "roleName",
		message: "What is the name of the role?",
		validate: (answer) => validateString(answer),
		when: (prev) => prev.select === "Add Role",
	},
	{
		type: "input",
		name: "roleSalary",
		message: "What is the salary of the role?",
		validate: (answer) => validateSalary(answer),
		when: (prev) => prev.select === "Add Role",
	},
	{
		type: "list",
		name: "roleDept",
		message: "What department does the role belong to?",
		choices: lists.deptList,
		when: (prev) => prev.select === "Add Role",
	},
	{
		type: "input",
		name: "employeeForename",
		message: "What is the employee's first name?",
		validate: (answer) => validateString(answer),
		when: (prev) => prev.select === "Add Employee",
	},
	{
		type: "input",
		name: "employeeSurname",
		message: "What is the employee's last name?",
		validate: (answer) => validateString(answer),
		when: (prev) => prev.select === "Add Employee",
	},
	{
		type: "list",
		name: "employeeRole",
		message: "What is the employee's role?",
		choices: lists.roleList,
		when: (prev) => prev.select === "Add Employee",
	},
	{
		type: "list",
		name: "employeeManager",
		message: "Who is the employee's manager?",
		choices: lists.employeeList,
		when: (prev) => prev.select === "Add Employee",
	},
	{
		type: "list",
		name: "updateRoleName",
		message: "Which employee do you want to update?",
		choices: lists.employeeList,
		when: (prev) => prev.select === "Update Employee Role",
	},
	{
		type: "list",
		name: "updateRoleRole",
		message: "What should their role be updated to?",
		choices: lists.roleList,
		when: (prev) => prev.select === "Update Employee Role",
	},
];

module.exports = questions;
